// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-M-zkK7jb-FJWnud-pQ9Yqi8S2UnXTA',
    appId: '1:343870592825:web:edd793715f091198343ae8',
    messagingSenderId: '343870592825',
    projectId: 'farmgo-1b78e',
    authDomain: 'farmgo-1b78e.firebaseapp.com',
    storageBucket: 'farmgo-1b78e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwkhOOMU1Bkm5ropP_EO58JyQgEOEoJs',
    appId: '1:343870592825:android:86770bd633cfd877343ae8',
    messagingSenderId: '343870592825',
    projectId: 'farmgo-1b78e',
    storageBucket: 'farmgo-1b78e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhDCJ3ReUABIH4LbIb6TaXZ8sVaXWQj64',
    appId: '1:343870592825:ios:1406f341ef967be4343ae8',
    messagingSenderId: '343870592825',
    projectId: 'farmgo-1b78e',
    storageBucket: 'farmgo-1b78e.appspot.com',
    iosClientId: '343870592825-tdb3tche5ib7l4qv2mqss9sj7sm6u0m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhDCJ3ReUABIH4LbIb6TaXZ8sVaXWQj64',
    appId: '1:343870592825:ios:1406f341ef967be4343ae8',
    messagingSenderId: '343870592825',
    projectId: 'farmgo-1b78e',
    storageBucket: 'farmgo-1b78e.appspot.com',
    iosClientId: '343870592825-tdb3tche5ib7l4qv2mqss9sj7sm6u0m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmgo',
  );
}
